name: hpipy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - requests
  - bioconductor-gosemsim
  - blast
  - biopython
  - networkx
  - python-levenshtein
  - matplotlib
  - diamond
  - colorama
  - hmmer
  - tqdm
  - scipy
  - rpy2
  - cd-hit
  - pandas
  - openpyxl
  